project:
  type: website
  output-dir: docs
  
website: 
  title: "yihan zhou"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: edu.qmd
        text: Intro
      #- href: basics.qmd
       # text: Basics
    #  - href: onelayernn.qmd
    #    text: Machine Learning Methods 
format: 
  html: 
    theme: cosmo
    toc: true
